apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: joiceqa
   environment: qa
 name: joiceqa
 namespace: joiceqa
# annotations:
#   template.alpha.openshift.io/wait-for-ready: 'true'
spec:
 replicas: 1
 selector:
  matchLabels:
   app: joiceqa
   environment: qa
 template:
  metadata:
   labels:
    app: joiceqa
    environment: qa
  spec:
#   imagePullSecrets:
#    - name: privregcred
   containers:
    - name: joiceqa
      image: " "
      resources:
        limits:
          cpu: '1'
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 256Mi
      ports:
       - containerPort: 3000
      livenessProbe:
        httpGet:
          path: /
          port: 3000
          scheme: HTTP
        initialDelaySeconds: 10
        timeoutSeconds: 2
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /
          port: 3000
          scheme: HTTP
        initialDelaySeconds: 30
        timeoutSeconds: 2
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3