apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: "@REPLACE_APP@"
   environment: "@REPLACE_ENV@"
 name: "@REPLACE_APP@"
 namespace: "@REPLACE_APP@"
spec:
 replicas: 1
 selector:
  matchLabels:
   app: "@REPLACE_APP@"
   environment: "@REPLACE_ENV@"
 template:
  metadata:
   labels:
    app: "@REPLACE_APP@"
    environment: "@REPLACE_ENV@"
  spec:
#   imagePullSecrets:
#    - name: privregcred
   containers:
    - name: "@REPLACE_APP@"
      image: " "
      resources:
        limits:
          cpu: '1'
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 256Mi
      ports:
       - containerPort: 3000
      livenessProbe:
        httpGet:
          path: /
          port: 3000
          scheme: HTTP
        initialDelaySeconds: 10
        timeoutSeconds: 2
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /
          port: 3000
          scheme: HTTP
        initialDelaySeconds: 30
        timeoutSeconds: 2
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3